### ISSUE TITLE
可以把微信读书加上？

### ISSUE THREAD

**Issue by ChitaGideon** [caspartse/eBooksAssistant#1]
微信读书里面东西挺多的，还是不错

**Comment by caspartse** [comment]
> 微信读书里面东西挺多的，还是不错
hi，最新版本已支持微信读书，https://greasyfork.org/en/scripts/412479-ebooks-assistant

**Comment by ChitaGideon** [comment]
https://weread.qq.com/

**Comment by ChitaGideon** [comment]
> > 微信读书里面东西挺多的，还是不错
> > hi，最新版本已支持微信读书，https://greasyfork.org/en/scripts/412479-ebooks-assistant

好吧，微信读书看来还有挺多书显示不出来；我还以为没加

**Comment by ChitaGideon** [comment]
```
Object
eBooks Assistant.user.js:216 Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object.onload (chrome-extension://ndcooeababalnlpkfedmmbbbgkljhpjf/eBooks%20Assistant.user.js:216:89)
    at <anonymous>:2:4475
    at <anonymous>:2:1659
    at <anonymous>:2:1886
    at HTMLDocument.<anonymous> (<anonymous>:2:16053)
eBooks Assistant.user.js:47 Uncaught TypeError: Cannot read properties of null (reading '1')
    at Object.onload (chrome-extension://ndcooeababalnlpkfedmmbbbgkljhpjf/eBooks%20Assistant.user.js:47:87)
    at <anonymous>:2:4475
    at <anonymous>:2:1659
    at <anonymous>:2:1886
    at HTMLDocument.<anonymous> (<anonymous>:2:16053)
```

一直在报错，不知道影不影响使用  @caspartse

**Comment by caspartse** [comment]
> > > 微信读书里面东西挺多的，还是不错
> > > hi，最新版本已支持微信读书，https://greasyfork.org/en/scripts/412479-ebooks-assistant
> 
> 好吧，微信读书看来还有挺多书显示不出来；我还以为没加

微信读书的 ISBN 不是必备项，多数情况下用标题等取搜索。
但微信读书启用的是全文搜索，所以出来的结果往往比较杂乱，本着宁缺勿滥的原则，不返回匹配度较低的结果。

**Comment by caspartse** [comment]
> ```
> Object
> eBooks Assistant.user.js:216 Uncaught TypeError: Cannot read properties of null (reading '1')
>     at Object.onload (chrome-extension://ndcooeababalnlpkfedmmbbbgkljhpjf/eBooks%20Assistant.user.js:216:89)
>     at <anonymous>:2:4475
>     at <anonymous>:2:1659
>     at <anonymous>:2:1886
>     at HTMLDocument.<anonymous> (<anonymous>:2:16053)
> eBooks Assistant.user.js:47 Uncaught TypeError: Cannot read properties of null (reading '1')
>     at Object.onload (chrome-extension://ndcooeababalnlpkfedmmbbbgkljhpjf/eBooks%20Assistant.user.js:47:87)
>     at <anonymous>:2:4475
>     at <anonymous>:2:1659
>     at <anonymous>:2:1886
>     at HTMLDocument.<anonymous> (<anonymous>:2:16053)
> ```
> 
> 一直在报错，不知道影不影响使用 @caspartse

已开源最新版本，可以试试还会不会出现。
