### ISSUE TITLE
无法使用，没有显示模块

### ISSUE THREAD

**Issue by lunula8** [caspartse/eBooksAssistant#7]
console提示：
TypeError: Cannot read properties of null (reading '1')
    at extractData (豆瓣读书助手.user.js:445:31)
    at doubanMain (豆瓣读书助手.user.js:428:22)
    at 豆瓣读书助手.user.js:500:9
    at 豆瓣读书助手.user.js:504:3
    at 豆瓣读书助手.user.js:505:3
    at Proxy.VMptmp5yzca6 (豆瓣读书助手.user.js:505:7)
    at Ut (injected-web.js:1:14789)
    at 豆瓣读书助手.user.js:1:20
    at async At (injected.js:1:8613)
    at async injected.js:1:13828

Uncaught SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at onload (豆瓣读书助手.user.js:297:33)
    at Boolean.HttpRequested (injected-web.js:1:6437)
    at Object.onHandle (injected-web.js:1:3056)
    at injected-web.js:1:3796

看其他人都没有提示这个问题，但我在隐私模式下排除了其他插件也没有恢复。之前用的好好的，是不是ip被ban了？我记得有一阵看2023豆瓣榜单的时候频繁使用这个插件，是不是频次高了被封？
如何确定自己ip是否被封，以及如何解除？

**Comment by caspartse** [comment]
谢谢反馈，豆瓣读书页面近期改版了，还没来得及作适配。预计过两周更新。

**Comment by lunula8** [comment]
原来这样，感谢。插件非常好用，期待修复~

**Comment by caspartse** [comment]
插件已升级，欢迎体验。
